sudo: required
services:
- docker
language: java
jdk:
- openjdk8
before_install:
- eval "$(gimme 1.13.4)"
- nvm install 12
- npm install -g npm@latest
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update
- sudo apt-get install gcc-4.8
- sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 50
- sudo apt-get install g++-4.8
- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50
script: mvn install
after_success:
- test "${TRAVIS_PULL_REQUEST}" == "false" && test "${TRAVIS_TAG}" != "" && ./travis/publish_to_bintray.sh
env:
  global:
  - secure: fqS3OabyL+omMi6eCwajizY6uVq9sXVFmpECPtAfMNsTDh3mh4I2zo6puSZszMWp1+Oc9I1ZO1TvJjrrbEuhfuONT7SMd8U2L8jmtXXLwv1AKn/3IpmAF9PvU723hO9oO5SZDU79dRrlaEDRnoJHeJh1PG2j2vtCEGNZCZ2btNGP5g00yHcMjMUU5kSI113iuRMQLyZuT7WaoCJO8GXXJfTx37seiW4c77Kj+1J/icVhcx4eF/ZOQRXgGAkZo7sPcmuKmBb95eUjgx3guiK2M1pU+oaivaOp1Qm4mkVE9W9p7zYThmrTvIElFHXbGEI9ATDYC+lhi764hj9IIicKF4c6Nghtl6rlrazbJvxYPbyMbURjnVEmzUFn0hhq8vwwBsoqbxJ07Vn0IAoYaAWq0pP9wWUuTYq0yD/BsiFbek4ewwki2QXjr5ZpMFiRymnyn4dqcKXApHL6wDSMmJZ/9ZSadHkOF4b4T3exNd4h6JA6OioErstlPimPjsi7rtR2IkedOYwcYmUKsJ2Wn5fOfNxI6Rg9HfGrtlM1wiIIMbxTxJduwPluuqsPQsu2gHPEXrjqyyE+A9fP1fQPF41vZXnSY+7iCzPn/bZsjSUohHS9GJQvfQ2Np6r2zAbhBo9zFaP7PVBh6IGpAMWYIFg7CQportIjv46pn6cP2e1MMhc=
  - secure: z11Ag3KuyLgbFqTWpB/Cue7q8qRpMwuLjF5ZiAegPJ8+L1rqk4LsMIJMuadKfmqC1ydv/jljrJmi6UeGLVwVnvUt8zl/2+TDjun9iceXxsLOoz4buP++oRA6m9fE5fj+1MBFhG5udtFZuvSaHGOftoIZ46JRG6/VAavfpx5M0Za+BbrVDZcyy+WLDE9H6nUdiQW7FteT3S0scJQQWn3Dkh6Jnu36nZ68/qQynZso7I+1PJ2SpRHkLuzRFbrC6oTvIbcfvjLsCbIMO76B1ERvOImovmf+Eurvji4CwdciMsKbUz8pQvtnNZyyYZdemQC5YjvUg3plHEwe/bOclVq4lwdBtz/JZncN/68iwyu+PgifiT35pnZ74S6Gurelp2IYWtrE7few7yg0JEaVP4hboM2cDI52RQF5yCMe0c/ntufv31o6/63BMHfGyioYf8m/qOLcQcOPdgeJExXkFCrn17JQU+TFYetLMfrG8/J51AdPIvRt7Hl4M+4vtxCBi37HtknVqljFsve5V31SHN/q5HMPA6Z26HCQNSaXD2O0TonqXf6eIqhjyw10JW+uzgniu/ChTwcbkrYxlg8qStrxUhhEhjNnRymY38As2+0I0EXlyaw3CdIhnkSB2LpLsXRDIeW47KipfG0AitIPZo3QuV8KC9RvI8ssQ3S3THfOREI=
